x-husarnet-config:
  &husarnet-config
  network_mode: service:husarnet
  depends_on: 
    husarnet: { condition: service_healthy } # husarnet service is healthy if all hosts listed in WAIT_HOSTNAMES are reachable

name: husarnet_listener
services:
  listener:
    build: .
    <<: *husarnet-config
    environment:
      - ROS_DISCOVERY_SERVER=talker-host:11811
    command: ros2 run demo_nodes_cpp listener

  husarnet:
    image: husarnet/husarnet:latest
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=listener-host
      - JOINCODE
      - HUSARNET_DEBUG=1
      - WAIT_HOSTNAMES=talker-host # hostname of host running Discovery Server